### ISSUE TITLE
Version 1.2.1: Cannot load fetchapi/base due to incorrect directory name

### ISSUE THREAD

**Issue by punkstar** [fetchapp/fetchapp-api-ruby#4]
```
/Users/nrj/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- fetchapi/base (LoadError)
from /Users/nrj/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
from /Users/nrj/.rvm/gems/ruby-1.9.3-p125/gems/fetchapp-api-ruby-1.2.1/lib/fetchapp-api-ruby.rb:6:in `<top (required)>'
from /Users/nrj/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
from /Users/nrj/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
from /Users/nrj/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
from ./find_purchases.rb:3:in `<main>'
```

It seems that the `base.rb` is referencing `fetchapi/base.rb`, while the folder structure is `fetchapp-api-ruby/base.rb` in the gem.

**Comment by mikelarkin** [comment]
Good Catch! Fixed in version 1.2.3

http://rubygems.org/gems/fetchapp-api-ruby
